//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNewAspWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Required]
        public int id { get; set; }

        [Required]
        [StringLength(35, ErrorMessage ="Name not be exceed")]
        public string name { get; set; }
        [Required]
        public string gender { get; set; }

        [Required]
        [Range(18,55,ErrorMessage ="Please Enter age between 18 and 55")]
        public int age { get; set; }
        [Required]
        public string designation { get; set; }
        [Required]
        public int salary { get; set; }
    }
}
